### ISSUE TITLE
assets not working

### ISSUE THREAD

**Issue by ahmetozalp** [coldi/r3f-game-demo#1]
![Ekran Resmi 2020-09-29 22 30 59](https://user-images.githubusercontent.com/7665820/94606702-876e2700-02a3-11eb-9694-5051a5e9f10e.png)

**Comment by djhi** [comment]
Had the same issue, download them from github site and replace the files you have locally

**Comment by ahmetozalp** [comment]
@djhi thank you working.


If I move this project to react native, do you think it will work, will I have performance problems?

**Comment by djhi** [comment]
No idea

**Comment by ahmetozalp** [comment]
thank you.
